version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "433:433" #HTTPS only in prod
    environment:
      - HTTPS_ONLY=True
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"